# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42a6f10ee01b63e7a2e338dd642b8ea65ec2a52d997498b33f66715f645559a6ff8f84937971e8c1395963ffe19b77e5e79c437652bd0a94c1796857a8c4830a

test:
  secret_key_base: a9bf551c8f0e1e22eb06ee923de5791dac412e08876874c7b12fcd4540ca0edcdee3479c14a4c1ee5a4570d309ed01193239ad672bf2f0095a6801d4372e9957

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

demo:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
